---
title: "Here's My Proposal"
description: |
  I'm graduating from college soon, and as a culmination of my higher education, I'm working on a Senior Project that leverages some of the skills I've gained over the last four years. 
date: 2021-09-22
output:
  distill::distill_article:
    self_contained: false
---

## Some Background

My favorite game is [Fortnite](https://www.epicgames.com/fortnite/en-US/home). Fortnite has a robust competitive community and consequently, there's loads of tournament data and player statistics that are publicly listed on [Fortnite Tracker](https://fortnitetracker.com/). But while the data is easy to view, it's not easy to collect, munge, or explore because their public API doesn't access competitive data. So to access this data, it needs to be web scraped. 

My project really has two main parts:
1. A python script that scrapes and stores the data in either a relational database, csv file, or `pandas` data frame. 
2. A dashboard or some series of charts that aptly visualizes the data collected from the event page. 

Just like professional sports, esports are in dire need of data analytics. This will be a great way for me to get my foot in the door in the esports industry. 

## Domain(s) to Investigate

I see two, maybe three domains. First, esports. Second, data science. And third, computer science. Since the vast majority of my free time is spent watching, learning, or playing Fortnite, I have a very solid understanding about the data I'm going to be working with. Most of my time is going to be spent learning how to collect the data, and how I'm going to visualize it in a professional way. And since I'm going to be writing a python script, I'm going to need to learn computer science techniques and practices on how best to scrape the data. 

## Proposed Deliverables

My main deliverable will be the dashboard or visualization that I make after I collect my data. But I can think of a few others if I have the time:
* An interactive website, or more likely a page on my blog, that houses the dashboard that I made.
* A relational database that contains all of the data I collect.
* A machine learning model that predicts the winner of the next major tournament based on results of previous tournaments (and various other factors that I could collect from Fortnite Tracker).

I'm looking forward to sharing my progress and bringing you along on this journey.
