---
title: "SypherPK x Metal Umbrella, Oni Studios"
date: 2021-07-29
output:
  distill::distill_article:
    self_contained: false
---

[SypherPK](https://twitter.com/SypherPK) just announced his new apparel brand, [Metal Umbrella](https://metalumbrella.com/). Sypher is a world-famous [Twitch streamer](https://www.twitch.tv/sypherpk), [YouTuber](https://www.youtube.com/sypherpk), and now, fashion icon. While no clothing has been revealed yet, the brand features a heavy anime aesthetic, referencing Sypher's love for Japanese animation. The first drop - titled "Too Young To Worry" - will be revealed Sunday, August 1st at 11 a.m. Central. It will be available for purchase on Thursday, August 5th. 

Thus continues [Oni Studios'](https://onistudios.gg/) ambitious climb towards the top of the esports, entertainment, and live-streaming industries. They specialize in all things content creation, helping creators build their brand, grow their audience, and manage their time and finances. They strive to be everything that was missing in this space: a loyal resource for burgeoning creators. 

I'm so impressed with what Sypher and his team have been able to do in the last year-and-a-half. Covid saw many industries struggle, but Sypher was perfectly posed to take full advantage of the opportunity. Since communities all across the world were in lockdown, people had more free time than perhaps ever before. People were playing more video games, watching more YouTube and Twitch, and Sypher capitalized on this new demographic. 

His YouTube subscriber base nearly tripled over that time, bringing daily, quality Fortnite content to millions (yes millions) of viewers. This success led to other opportunities, such as new brand partnernships, [an exclusive streaming deal with Twitch](https://www.tubefilter.com/2020/11/10/sypherpk-twitch-deal-talent-incubator/), and the creation of Oni Studios.

The sky's the limit with this team, I'm excited to see what they do next. 

