---
title: "Solo Cash Cup - July 18, 2021"
date: 2021-07-18
output:
  distill::distill_article:
    self_contained: false
---

## Europe

Fresh off the heels of his third FNCS victory, [Falcon TaySon](https://twitter.com/taysonFN?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) won the 1st solo cash cup of the season in convincing fashion, confirming what the majority of the Fortnite community already knows - that TaySon is far and away the best player alive. He finished with 183 points, two victory royales, and an average placement of 16.2. 

As awesome as his performance was, I don't think that was the biggest story of the day. [FaZe Mongraal](https://twitter.com/Mongraal) placed 11th , complete with perhaps the [most impressive late-game pop off](https://twitter.com/FaZeClan/status/1416797717548896256) I've seen this year. After not qualifying for FNCS Grand Finals two seasons in a row, struggling to find a consistent trio (all while playing the game less than he ever has) Mongraal made a commitment to turn things around, get back on the grind, and strive to be the best. Well, the practice seems to be paying off. Hopefully this is just the beginning of a much deserved comeback. 

[NRG benjyfishy](https://twitter.com/benjyfishy), on the other hand, had a less than ideal tournament. He placed 2,647th with two victory royales, but with an average placement of 56.8. I don't think this is worrisome at all as he placed 5th in the [UEFA Euro cup](https://twitter.com/benjyfishy/status/1405607291257245698) last month, and solos aren't the main game mode anyway. His attention remains on qualifying for Trio FNCS and hopefully, finally, winning the Axe of Champions.

## North America East

[DL Justice](https://twitter.com/Justicee) won comfortably with 184 points, three victory royales, and average placement of 36.4. His worst placement of the day was an 88th place, but three 1st's and a 2nd was enough to win him the tournament - racking up 38 eliminations along the way. 

[1% Acorn](https://twitter.com/AcornFN), [Tragix](https://twitter.com/tragix_), and [FaZe Dubs](https://twitter.com/Dubsfn) placed 3rd, 4th, and 5th respectively. Tragix has been seeing quite a bit of success in solo tournements, placing 5th in the FNCS All-Star Showdown grand finals. Same story for Dubs who placed just below Tragix, getting 5th. Dubs and Tragix have been playing out of their minds recently and I'm excited to see if they can capitalize once Trio FNCS kicks off in the coming weeks. 

The story for NAE cash cups remains the same - a European player(s) will play very aggressively, shoot to the top of the leaderboard, but refuse to play for end game, leaving the door wide open for North American players to take the lead. This happens almost every tourney. Yes, EU has the better, smarter, more mechanical players - but they just get impatient playing on East. Doesn't help playing on 80 plus ping either...

## Solos

I've always been a bigger fan of solo tournaments than team-based tournaments. I play a lot of solos myself, so I find the gameplay more fun to watch. It's a shame we won't get any bigger solo tourneys for the forseeable future as trios is the main game mode for the remainder of the year. I'd also like to see some more high-profile duo and squads tournaments as trios are getting a bit stale, but Fortnite's Fortnite and I'll watch every tournament no matter what. 




